//! bash's two files: a generated interactive file sourced from a fixed region
//! in `~/.bashrc`, and `~/.inputrc`.
//!
//! bash gets the declarations it shares with zsh, each in its own words, and
//! nothing else. The rest of a distribution's bash setup — its prompt, its
//! terminal title, its completion — stays the distribution's: bx adds one
//! region to `~/.bashrc` and never ports or replaces a byte around it.
//!
//! | file                                  | holds                                          | attached as          |
//! |---------------------------------------|------------------------------------------------|----------------------|
//! | [`FILE`], `~/.local/share/bx/bashrc.bash` | the aliases, then `[history]` and `[shell-options]` | a file bx owns whole |
//! | [`STARTUP_FILE`], `~/.bashrc`         | the one line that sources [`FILE`]              | a fixed region       |
//! | [`INPUTRC`], `~/.inputrc`             | `[keybindings]`, in readline's syntax           | a file bx owns whole |
//!
//! # The interactive file
//!
//! [`Bash::render`] assembles it through the same [`Assembly`] zsh's file is,
//! in two of its phases. The `aliases` phase holds every enabled alias as
//! [`AliasDecl::render_bash`] renders it: the same line zsh gets, a
//! `has:TOOL` decided while `plan` renders exactly as zsh's is, and a runtime
//! condition asked in bash's words. The `options` phase holds the declared
//! `[history]` as [`History::render_bash`] renders it, then the declared
//! `[shell-options]` as [`ShellOptions::render_bash`] renders them.
//!
//! The file is placed when an enabled alias is declared — gated on a missing
//! tool or not, as zsh's is — or a history or shell option bash reads. Its
//! region in `~/.bashrc` is the one [`crate::config::env`] attaches to every
//! zsh startup file: the region's delimiters around one line that sources the
//! file only when it is readable. Its bytes name the file and nothing else, so
//! they are the same for every declaration and every account.
//!
//! None of it holds a placeholder, so nothing here is ever held back.
//!
//! # `~/.inputrc`
//!
//! Readline reads `~/.inputrc` in place of the system's `/etc/inputrc`
//! whenever the first exists, so the file bx writes opens by including the
//! system's — a missing one is skipped silently — and then binds the declared
//! keys ([`Keybindings::render_readline`]), which therefore win. Its header
//! says the bindings reach every program linked against readline, not only
//! bash. It is placed when any key is bound, and it is a file bx owns whole:
//! an `~/.inputrc` bx did not write is a conflict the plan reports, never
//! overwritten.
//!
//! # When a declaration goes away
//!
//! [`vacated`] plans the file and `~/.inputrc` with nothing declared in them
//! once nothing places either but bx's generator for it wrote it before, as
//! [`crate::config::resolve::vacated_fragments`] does for zsh's fragments; the
//! region is left sourcing a file that sets nothing, and `bx rm` restores
//! each file from the ledger.
//!
//! # Invariant 2
//!
//! Neither file is an environment fragment. The `aliases` phase defines
//! aliases and nothing else; the `options` phase assigns only bash's own
//! history variables and then unexports them, and `shopt` assigns nothing.
//! The history file is the one path either names, and the plan judges it
//! against bx's own directories as it judges zsh's. An inputrc is readline's
//! syntax, which has no variable of the environment's at all.
//! `bash_defines_the_aliases_and_changes_only_its_history_variables` runs the
//! whole rendered file in bash and holds it to that.

use std::path::Path;

use super::alias::AliasDecl;
use super::keybindings::Keybindings;
use super::{Assembly, Phase};
use crate::config::history::{self, History};
use crate::config::resolve::Resolution;
use crate::config::shell_options::{self, ShellOptions};
use crate::config::target::{Attach, Body, Direction, Format, Gen, Target};
use crate::config::{Config, Error, Origin};
use crate::paths::Portable;

/// bash's generated interactive file, which bx owns whole.
pub const FILE: &str = "~/.local/share/bx/bashrc.bash";

/// The user's startup file whose region sources [`FILE`].
pub const STARTUP_FILE: &str = "~/.bashrc";

/// Readline's own file, which bx owns whole once a key is bound.
pub const INPUTRC: &str = "~/.inputrc";

/// The lines `~/.inputrc` opens with: whose it is, and whom it reaches.
const INPUTRC_HEADER: &str = "# Generated by bx from [keybindings]. Edit the config repo, not this \
                              file.\n# Readline reads these bindings in every program linked \
                              against it, not only bash.\n";

/// The line that keeps the system's bindings, which readline would otherwise
/// stop reading once `~/.inputrc` exists. Readline skips an include it cannot
/// open.
const INCLUDE_SYSTEM: &str = "$include /etc/inputrc\n";

/// What bash's generated interactive file holds.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Bash {
    /// The enabled aliases, in the merged configuration's order.
    aliases: Vec<AliasDecl>,
    /// The declared history, rendered in bash's names.
    history: History,
    /// The declared shell options.
    options: ShellOptions,
}

impl Bash {
    /// The file holding `aliases` — the disabled ones dropped — `history` and
    /// `options`.
    #[must_use]
    pub fn new(aliases: &[AliasDecl], history: History, options: ShellOptions) -> Self {
        Self {
            aliases: aliases.iter().filter(|a| a.enabled).cloned().collect(),
            history,
            options,
        }
    }

    /// The declared history, whose bash file the plan judges.
    #[must_use]
    pub const fn history(&self) -> &History {
        &self.history
    }

    /// What places the file: the first enabled alias, else the history when
    /// it says anything bash reads, else the shell options when they do.
    /// `None` when nothing does.
    fn origin(&self) -> Option<&Origin> {
        self.aliases
            .first()
            .map(|alias| &alias.origin)
            .or_else(|| {
                self.history
                    .origin
                    .as_ref()
                    .filter(|_| !self.history.render_bash().is_empty())
            })
            .or_else(|| {
                self.options
                    .origin
                    .as_ref()
                    .filter(|_| !self.options.render_bash().is_empty())
            })
    }

    /// The file's bytes.
    ///
    /// `present` answers whether a `has:TOOL` tool is usable on this machine,
    /// as it does for zsh's file. A phase with nothing in it is left out, so
    /// the bytes are a function of the declarations and `present` alone.
    #[must_use]
    pub fn render(&self, present: &dyn Fn(&str) -> bool) -> String {
        // Neither phase is the terminal slot, so no contribution is refused.
        let mut assembly = Assembly::new();
        for alias in &self.aliases {
            let body = alias.render_bash(present);
            if !body.is_empty() {
                let _ = assembly.contribute(Phase::Aliases, alias.name.clone(), body);
            }
        }
        let _ = assembly.contribute(Phase::Options, history::SECTION, self.history.render_bash());
        let _ = assembly.contribute(
            Phase::Options,
            shell_options::SECTION,
            self.options.render_bash(),
        );
        assembly.render()
    }
}

/// `~/.inputrc`'s bytes: the header, the system's bindings included, then
/// the declared ones.
#[must_use]
pub fn render_inputrc(keybindings: &Keybindings) -> String {
    format!(
        "{INPUTRC_HEADER}{INCLUDE_SYSTEM}{}",
        keybindings.render_readline()
    )
}

/// The targets bash's files make: [`FILE`] and its region in
/// [`STARTUP_FILE`] when anything places the file, and [`INPUTRC`] when a key
/// is bound. Each is attributed to the declaration that placed it.
///
/// # Errors
///
/// [`Error::BadValue`] when `home` cannot hold the files' paths.
pub fn place(merged: &Config, home: &Path) -> Result<Vec<Resolution<Target>>, Error> {
    let bash = Bash::new(
        &merged.aliases,
        merged.history.clone(),
        merged.shell_options.clone(),
    );
    let mut placed = Vec::new();
    if let Some(origin) = bash.origin().cloned() {
        let file = portable(FILE, home, &origin)?;
        let region = portable(STARTUP_FILE, home, &origin)?;
        placed.push(Resolution::Ready(target(
            file.clone(),
            Gen::Bash(Box::new(bash)),
            Attach::Own,
            &origin,
        )));
        placed.push(Resolution::Ready(target(
            region,
            Gen::Source(file),
            Attach::Region { comment: '#' },
            &origin,
        )));
    }
    let keybindings = &merged.keybindings;
    if let Some(origin) = keybindings
        .origin
        .as_ref()
        .filter(|_| !keybindings.is_empty())
    {
        placed.push(Resolution::Ready(target(
            portable(INPUTRC, home, origin)?,
            Gen::Inputrc(keybindings.clone()),
            Attach::Own,
            origin,
        )));
    }
    Ok(placed)
}

/// [`FILE`] and [`INPUTRC`] with nothing declared in them, for each one
/// `placed` does not name but `generated` says bx wrote with the generator
/// that makes it, attributed to `origin`.
///
/// Without it, removing every alias would leave them defined in every bash
/// that starts, and unbinding every key would leave the keys bound, with no
/// plan row saying so.
///
/// `generated(path, header)` answers whether bx wrote `path` as a file it
/// owns whole and the bytes there open with `header`, the line that file's
/// generator writes first. Owning the file whole is not enough: a
/// `[[target]]` the user once declared at `~/.inputrc` is owned whole too,
/// and once dropped it is left alone as every dropped target is, never
/// rewritten to an inputrc with no bindings in it.
#[must_use]
pub fn vacated(
    placed: &[Resolution<Target>],
    generated: &dyn Fn(&Portable, &str) -> bool,
    home: &Path,
    origin: &Origin,
) -> Vec<Resolution<Target>> {
    [
        (FILE, super::HEADER, Gen::Bash(Box::default())),
        (
            INPUTRC,
            INPUTRC_HEADER,
            Gen::Inputrc(Keybindings::default()),
        ),
    ]
    .into_iter()
    .filter_map(|(raw, header, generator)| {
        let path = Portable::parse_in(raw, home).ok()?;
        let named = placed.iter().any(|resolution| match resolution {
            Resolution::Ready(target) => target.path == path,
            Resolution::Blocked(entry) => entry.key == path.to_string(),
        });
        (!named && generated(&path, header))
            .then(|| Resolution::Ready(target(path, generator, Attach::Own, origin)))
    })
    .collect()
}

/// `raw` under `home`, or the error naming `origin` when it cannot be.
fn portable(raw: &str, home: &Path, origin: &Origin) -> Result<Portable, Error> {
    Portable::parse_in(raw, home).map_err(|source| Error::BadValue {
        origin: origin.clone(),
        message: format!("`{raw}` cannot be placed under this home: {source}"),
    })
}

/// A target bash's files make, produced by `generator`.
fn target(path: Portable, generator: Gen, attach: Attach, origin: &Origin) -> Target {
    Target {
        path,
        body: Body::Generated(generator),
        mode: None,
        attach,
        direction: Direction::Apply,
        format: Format::Opaque,
        requires: Vec::new(),
        references: Vec::new(),
        enabled: true,
        origin: origin.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::parse_str;
    use crate::shell::testing::{installed, run};
    use std::path::PathBuf;

    const HOME: &str = "/var/home/example";

    fn load(text: &str) -> Config {
        parse_str(text, Path::new("/repo/bx.toml"), Path::new(HOME)).expect("parses")
    }

    fn bash_of(config: &Config) -> Bash {
        Bash::new(
            &config.aliases,
            config.history.clone(),
            config.shell_options.clone(),
        )
    }

    /// Each target's path, how it is attached, and its bytes on a machine
    /// with every tool.
    fn described(placed: &[Resolution<Target>]) -> Vec<(String, Attach, String)> {
        placed
            .iter()
            .map(|resolution| match resolution {
                Resolution::Ready(target) => {
                    let Body::Generated(generator) = &target.body else {
                        panic!("a generated body: {target:?}");
                    };
                    (
                        target.path.to_string(),
                        target.attach.clone(),
                        generator.render(&|_| true),
                    )
                }
                Resolution::Blocked(entry) => panic!("nothing is held back: {entry:?}"),
            })
            .collect()
    }

    /// The source configuration's shared declarations.
    const SOURCE: &str = "[aliases]\nll = \"ls -la\"\nsudo = \"sudo \"\n\n\
                          [[alias]]\nname = \"cat\"\ncommand = \"bat --paging=never\"\n\
                          when = \"has:bat\"\n\n\
                          [[alias]]\nname = \"off\"\ncommand = \"x\"\nenabled = false\n\n\
                          [history]\nsize = 10000\nduplicates = \"all\"\n\
                          ignore_space = true\nshare = true\n\n\
                          [history.file]\nzsh = \"~/.zsh_history\"\nbash = \"~/.bash_history\"\n\n\
                          [shell-options]\nhistappend = true\ncheckwinsize = true\n\n\
                          [keybindings]\nhome = \"beginning-of-line\"\nalt-b = \"backward-word\"\n";

    const RENDERED: &str = "# Generated by bx. Edit the config repo, not this file.\n\
                            \n# bx phase: aliases\n\
                            alias ll='ls -la'\nalias sudo='sudo '\n\
                            alias cat='bat --paging=never'\n\
                            \n# bx phase: options\n\
                            HISTFILE=\"${HOME}/.bash_history\"\n\
                            HISTSIZE=10000\nHISTFILESIZE=10000\n\
                            HISTCONTROL=ignorespace:erasedups\n\
                            export -n HISTFILE HISTSIZE HISTFILESIZE HISTCONTROL\n\
                            shopt -s checkwinsize histappend\n";

    #[test]
    fn the_file_holds_the_aliases_then_history_and_shell_options_in_bash_words() {
        let bash = bash_of(&load(SOURCE));
        assert_eq!(bash.render(&|_| true), RENDERED);
        // Twice, the same bytes.
        assert_eq!(bash.render(&|_| true), bash.render(&|_| true));
        // A missing tool leaves its alias out, and asks the shell nothing.
        let without_bat = bash.render(&|tool| tool != "bat");
        assert_eq!(
            without_bat,
            RENDERED.replace("alias cat='bat --paging=never'\n", "")
        );
        assert!(!without_bat.contains("command -v"), "{without_bat}");
        // A runtime condition is asked in bash's words.
        let gated = bash_of(&load(
            "[[alias]]\nname = \"g\"\ncommand = \"git\"\nwhen = \"login\"\n",
        ));
        assert!(
            gated
                .render(&|_| true)
                .ends_with("if shopt -q login_shell; then\n  alias g='git'\nfi\n"),
            "{}",
            gated.render(&|_| true)
        );
        // Nothing declared: the header alone.
        assert_eq!(
            Bash::default().render(&|_| true),
            "# Generated by bx. Edit the config repo, not this file.\n"
        );
    }

    #[test]
    fn the_inputrc_includes_the_system_file_then_binds_the_declared_keys() {
        let keybindings = load(SOURCE).keybindings;
        assert_eq!(
            render_inputrc(&keybindings),
            "# Generated by bx from [keybindings]. Edit the config repo, not this file.\n\
             # Readline reads these bindings in every program linked against it, not only \
             bash.\n\
             $include /etc/inputrc\n\
             \"\\e[H\": beginning-of-line\n\
             \"\\eb\": backward-word\n"
        );
        assert_eq!(
            render_inputrc(&Keybindings::default()),
            format!("{INPUTRC_HEADER}{INCLUDE_SYSTEM}")
        );
    }

    #[test]
    fn every_declaration_places_the_file_its_region_and_the_inputrc() {
        let placed = place(&load(SOURCE), Path::new(HOME)).expect("places");
        let described = described(&placed);
        assert_eq!(
            described,
            vec![
                (FILE.to_string(), Attach::Own, RENDERED.to_string()),
                (
                    STARTUP_FILE.to_string(),
                    Attach::Region { comment: '#' },
                    format!("[[ -r {FILE} ]] && source {FILE}\n"),
                ),
                (
                    INPUTRC.to_string(),
                    Attach::Own,
                    render_inputrc(&load(SOURCE).keybindings),
                ),
            ]
        );
        // The file and its region are attributed to the first alias, the
        // inputrc to its table.
        let lines: Vec<usize> = placed
            .iter()
            .map(|resolution| match resolution {
                Resolution::Ready(target) => target.origin.line,
                Resolution::Blocked(_) => unreachable!(),
            })
            .collect();
        assert_eq!(lines, [2, 2, 29]);
    }

    #[test]
    fn each_declaration_places_the_file_on_its_own_and_only_bash_s_words_count() {
        let paths = |text: &str| -> Vec<String> {
            place(&load(text), Path::new(HOME))
                .expect("places")
                .iter()
                .map(|resolution| match resolution {
                    Resolution::Ready(target) => {
                        format!("{}@{}", target.path, target.origin.line)
                    }
                    Resolution::Blocked(_) => unreachable!(),
                })
                .collect()
        };
        let file = |line: usize| vec![format!("{FILE}@{line}"), format!("{STARTUP_FILE}@{line}")];
        assert_eq!(paths("[aliases]\nll = \"ls\"\n"), file(2));
        // Gated on a tool, the alias still places the file, as zsh's does.
        assert_eq!(
            paths("[[alias]]\nname = \"c\"\ncommand = \"bat\"\nwhen = \"has:bat\"\n"),
            file(1)
        );
        assert_eq!(paths("[history]\nsize = 5\n"), file(1));
        assert_eq!(paths("\n[shell-options]\nhistappend = false\n"), file(2));
        assert_eq!(
            paths("[keybindings]\nend = \"end-of-line\"\n"),
            [format!("{INPUTRC}@1")]
        );
        // What bash does not read places nothing.
        for text in [
            "",
            "[[alias]]\nname = \"off\"\ncommand = \"x\"\nenabled = false\n",
            "[history]\nshare = true\n",
            "[history.file]\nzsh = \"~/.zsh_history\"\n",
            "[shell-options]\n",
            "[keybindings]\n",
        ] {
            assert!(paths(text).is_empty(), "{text}");
        }
    }

    #[test]
    fn a_file_bx_wrote_that_nothing_places_any_more_is_planned_empty() {
        let home = Path::new(HOME);
        let origin = Origin {
            file: PathBuf::from("/state/ledger"),
            line: 0,
        };
        let every = vacated(&[], &|_, _| true, home, &origin);
        assert_eq!(
            described(&every),
            vec![
                (
                    FILE.to_string(),
                    Attach::Own,
                    Bash::default().render(&|_| true)
                ),
                (
                    INPUTRC.to_string(),
                    Attach::Own,
                    render_inputrc(&Keybindings::default())
                ),
            ]
        );
        // Never one bx did not write, and never one still placed.
        assert!(vacated(&[], &|_, _| false, home, &origin).is_empty());
        let placed = place(&load(SOURCE), home).expect("places");
        assert!(vacated(&placed, &|_, _| true, home, &origin).is_empty());
        // Each file is asked after with its own generator's header, so one
        // bx owns whole but some other declaration wrote is left alone.
        let inputrc_only = |path: &Portable, header: &str| {
            path.as_str() == INPUTRC && render_inputrc(&Keybindings::default()).starts_with(header)
        };
        assert_eq!(
            described(&vacated(&[], &inputrc_only, home, &origin))
                .into_iter()
                .map(|(path, _, _)| path)
                .collect::<Vec<_>>(),
            vec![INPUTRC.to_string()]
        );
        let bash_only = |path: &Portable, header: &str| {
            path.as_str() == FILE && Bash::default().render(&|_| true).starts_with(header)
        };
        assert_eq!(
            described(&vacated(&[], &bash_only, home, &origin))
                .into_iter()
                .map(|(path, _, _)| path)
                .collect::<Vec<_>>(),
            vec![FILE.to_string()]
        );
    }

    #[test]
    fn bash_defines_the_aliases_and_changes_only_its_history_variables() {
        let Some(bash) = installed("bash") else {
            return;
        };
        let rendered = bash_of(&load(SOURCE)).render(&|_| true);
        let flags = ["--norc", "--noprofile"];
        let probe = "printf '%s|' \"${BASH_ALIASES[ll]}\" \"${BASH_ALIASES[sudo]}\" \
                     \"${BASH_ALIASES[cat]}\" \"$HISTSIZE\" \"$HISTCONTROL\"; \
                     shopt -p checkwinsize histappend\n";
        let got =
            String::from_utf8(run(&bash, &flags, &format!("{rendered}{probe}"))).expect("utf-8");
        assert_eq!(
            got,
            "ls -la|sudo |bat --paging=never|10000|ignorespace:erasedups|\
             shopt -s checkwinsize\nshopt -s histappend\n"
        );

        // Invariant 2: only the history variables change, and nothing is
        // exported, even what an exported parent set. `BASHOPTS` is bash's
        // report of its options, which `shopt` is declared to change.
        let dump = "__bx_dump() { local n; for n in $(compgen -v); do case $n in \
                    BASH_*|BASHOPTS|FUNCNAME|_|n|LINENO|RANDOM|SECONDS|SRANDOM|EPOCH*|\
                    PIPESTATUS) continue;; esac; printf '%s=%s\\n' \"$n\" \"${!n}\"; done; \
                    printf 'exported: %s\\n' $(compgen -e); printf -- '---\\n'; }\n";
        let dumps = |body: &str| {
            let script = format!("export HISTSIZE=1\n{dump}__bx_dump\n{body}__bx_dump\n");
            let got = String::from_utf8(run(&bash, &flags, &script)).expect("utf-8");
            let (before, after) = got.split_once("---\n").expect("two dumps");
            (
                before.to_string(),
                after.trim_end_matches("---\n").to_string(),
            )
        };
        let (before, after) = dumps(&rendered);
        let mut changed: Vec<&str> = after
            .lines()
            .filter(|line| !before.lines().any(|was| was == *line))
            .map(|line| line.split('=').next().expect("a name"))
            .collect();
        changed.sort_unstable();
        assert_eq!(
            changed,
            ["HISTCONTROL", "HISTFILE", "HISTFILESIZE", "HISTSIZE"],
            "{before}\n---\n{after}"
        );
        assert!(before.contains("exported: HISTSIZE"), "{before}");
        assert!(!after.contains("exported: HIST"), "{after}");
        // The dump does see an assignment, so the comparison means something.
        let (before, after) = dumps("Z=1\n");
        assert_ne!(after, before);
    }

    #[test]
    fn readline_reads_the_inputrc_as_the_declared_bindings() {
        let Some(bash) = installed("bash") else {
            return;
        };
        let scratch = tempfile::tempdir().expect("a scratch directory");
        let inputrc = scratch.path().join("inputrc");
        std::fs::write(&inputrc, render_inputrc(&load(SOURCE).keybindings)).expect("write");
        let script = format!(
            "bind -f {}\nbind -q beginning-of-line\nbind -q backward-word\n",
            inputrc.display()
        );
        let got = String::from_utf8(run(&bash, &["--norc", "--noprofile", "-i"], &script))
            .expect("utf-8");
        // Readline spells an escape-prefixed sequence `\M-` where
        // `convert-meta` is on and `\e` where it is off. The inputrc includes
        // the system's, which decides that setting (Fedora's turns it off,
        // Ubuntu's leaves it on), and both spellings name the same keys.
        let got = got.replace("\\M-", "\\e");
        assert!(
            got.contains("beginning-of-line can be invoked via") && got.contains("\"\\e[H\""),
            "{got}"
        );
        assert!(
            got.contains("backward-word can be invoked via") && got.contains("\"\\eb\""),
            "{got}"
        );
    }
}
